enum ErrorCode {
  ORIGIN_LINK_REQUIRED,
  INVALID_OAUTH_CODE,
  ORIGIN_UNAVAILABLE,
  UNKNOWN,
  NETWORK_ERROR,
  MISSING_OAUTH_CODE,
  ACCOUNT_INACTIVE,
  NO_PERMISSION,
  TIMEOUT_ERROR,
}

export default ErrorCode;
